### ISSUE TITLE
New Core

### ISSUE THREAD

**Issue by azumbrunnen** [OpenEmu/PPSSPP-Core#14]
hey guys

really love the smooth integration! any chance we'll see the new core integrated soon?

**Comment by clobber** [comment]
???

We already use PPSSPP 1.3 which is the latest stable release and available for OpenEmu 2.0+

**Comment by danilobytes** [comment]
What about an update to 1.4.x which was recently released?

**Comment by danilobytes** [comment]
Sorry for asking again, but are there any plans on adding any newer version?

**Comment by clobber** [comment]
@danilobytes Stop asking. Core plugins get updated, when they get updated. Learn to contribute something other than noise in our issues that generates useless emails.
