### ISSUE TITLE
New release soon? Or save transfers with autonomous emulator?

### ISSUE THREAD

**Issue by metamatik** [OpenEmu/PPSSPP-Core#16]
Hello,

First of all, thank you for the great work you do here :)

I am wondering if there is any chance you will release soon a new version of the core based on v1.4.2 of the emulator. Long story short, after playing tens of hours of Puzzle Quest, I happened a couple of days ago upon what seems to be a completely blocking bug, and it seems like my only hope now is that it _might_ not happen with an updated core.

Alternatively, is there a way, unknown to me, to save my game in OpenEmu and reopen the save file with an autonomous version of PPSSPP? I couldn't find any relevant information online, but any pointer you might be able to give me might help this desperate gamer ^^;

Thanks in advance :)

**Comment by clobber** [comment]
1.4.2 is available now. We don't normally comment on core updates as they go unplanned.

You can probably figure out how to transfer your save files around by reading this: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

Can't help you beyond that though. It's unsupported.
