### ISSUE TITLE
Tactics Ogre - Blurry text in 1.4.2

### ISSUE THREAD

**Issue by dmayle1** [OpenEmu/PPSSPP-Core#17]
I am having issues with the new PPSSPP core update. Is there a way to rollback to the 1.3 version? I downloaded the 1.3 version and replaced it in the cores section on Open emu. But whenever I start it back up it auto updates to 1.42.

**Comment by clobber** [comment]
There isn't. What issue?

**Comment by dmayle1** [comment]
I'm playing tactics ogre for PSP which has been working great over the past few months. Since the update the text is extremely blurry and really hard to read.

**Comment by clobber** [comment]
This is a PPSSPP bug upstream (https://github.com/hrydgard/ppsspp/issues/9779). They fixed it for next release so you will have to wait until then.

**Comment by clobber** [comment]
https://github.com/OpenEmu/PPSSPP-Core/compare/8ded57e0802d...92f6d7a49edc

This is fixed now after merging a patch from upstream.

Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.4.2.1.
