### ISSUE TITLE
Language of the PPSSPP-core

### ISSUE THREAD

**Issue by Antoninlefebvre** [OpenEmu/PPSSPP-Core#24]
Hi!
None of all the precedent topics has resolved the problem which is : how can we change manually (with the terminal) the initial language of the psp in PPSSPP-Core. Is it impossible ?
A solution was found for the desmume (consisting in changing some numbers into the number of the corresponding language) but not for PPSSPP...
Thank you so much

**Comment by clobber** [comment]
Do not open duplicate issues.
