### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Ponk91** [OpenEmu/PPSSPP-Core#8]
Hi there, I've tried to use a few different version of god of war games but it keeps saying that this version of the PPSSPP core has compatibility issues. When I play it's really glitchy, I noticed this issue has been brought up before. Do I just wait for a new update or is there something I can do?

Thank you

Ponk91

**Comment by clobber** [comment]
Well we don't develop the emulators. If there are compatibility issues in PPSSPP that is up to the emulator developers to correct. We post this notice for a reason, which as you can read, states please do not report any issues:

![screen shot 2015-12-29 at 7 27 07 pm](https://cloud.githubusercontent.com/assets/1303132/12045507/46add534-ae62-11e5-9a4d-9108a89767dc.png)
